#!/bin/bash

#default_img=/lib/cd../default.txt # default iamge
#text="$(< $default_img)"

# Reset
color_off='\033[0m'       # Text Reset
#'\033[0;37m'             # White
#'\033[0;30m'             # Black

# Regular Colors
color1=(
'\033[0;35m'         # Purple
'\033[0;35m'         # Purple
'\033[0;31m'         # Red
'\033[0;31m'         # Red
'\033[93m'           # Yellow
'\033[93m'           # Yellow
'\033[0;32m'         # Green
'\033[0;32m'         # Green
'\033[1;36m'         # Cyan
'\033[1;36m'         # Cyan
'\033[1;34m'         # Light Blue
'\033[1;34m'         # Light Blue
)

# Regular Colors
color2=(
'\033[0;31m'         # Red
'\033[0;31m'         # Red
'\033[0;33m'         # Orange
'\033[0;33m'         # Orange
'\033[1;33m'           # Yellow
'\033[1;33m'           # Yellow
'\033[0;32m'         # Green
'\033[0;32m'         # Green
'\033[1;36m'         # Cyan
'\033[1;36m'         # Cyan
'\033[1;34m'         # Light Blue
'\033[1;34m'         # Light Blue
'\033[0;35m'         # Purple
'\033[0;35m'         # Purple
)

function add_color() {
    color=("${color2[@]}")
    text="$1"
    arr=()
    while read -r line; do
    arr+=("$line")
    done <<< "$text"

    for (( j=0; j<${#arr[@]}; j++ )); do
    #for j in "${arr[@]}"
    #do
        line=${arr[j]}
        newline=""
        for (( k=0; k<${#line}; k++ )); do
            newline="$newline${color[$((($k+$j)%(${#color[@]})))]}${line:$k:1}${color_off}"
        done
        arr[j]=$newline
        #echo "${arr[j]}"
    done

    fin="${arr[0]}"
    for (( m=1; m<${#arr[@]}; m++ )); do
        fin="$fin\n${arr[$m]}"
    done

    echo -e $fin
    #return fin
}