#!/bin/bash
LIB_FILE="/usr/local/lib"   # the directory for the library
BIN_FILE="/usr/local/bin"   # the directory for the binary
{ # try

    echo -n "removing softlink: $BIN_FILE/cd.. ..." &&
    sudo rm $BIN_FILE/cd.. &&
    echo "Done" &&

    echo -n "removing $LIB_FILE/cd../default.txt..." &&
    sudo rm $LIB_FILE/cd../default.txt &&
    echo "Done" &&

    echo -n "removing $LIB_FILE/cd../colorful_print..." &&
    sudo rm $LIB_FILE/cd../colorful_print &&
    echo "Done" &&

    echo -n "removing $LIB_FILE/cd.. ..." &&
    sudo rmdir $LIB_FILE/cd.. &&
    echo "Done" &&

    echo -n "removing .cd.." &&
    sudo rm -rf ../.cd.. &&
    echo "Done" &&
    echo "All files Deleted!"

} || { # catch
    echo "Error while removing files"
    exit 1 
}


